AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "*.gemspec"

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "spec/**/*.rb"

Metrics/ClassLength:
  Max: 1500
  
Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 1500
  Exclude:
    - "spec/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false # avoids dangling object pointers
